### ISSUE TITLE
completeness?

### ISSUE THREAD

**Issue by jpka** [Serg-Norseman/NorseWorld-Ragnarok#1]
How much of the original is implemented?

**Comment by Serg-Norseman** [comment]
Difficult question. It is necessary to think.
In the last months of development in 2008, I estimated the completion rate at 90-95%. But I could be wrong.

Worlds and levels were realized completely, all the transitions between them, all the quests and quest items. Also fully implemented are all items, races and creatures, in their entirety (by contents). Also all effects (magic or abilities) of objects and creatures are made. That is, I just took the original guide to the game, wrote the editor of the game files for the original and then gradually explored all the logic and behavior of the game. In complex cases, I repeatedly added the necessary items or artifacts to my saved games and step by step, studied those or other events.

We also added a lot of our own features, because wanted a much more detailed world of Scandinavian myths. Therefore, there are differences. Quite a lot of new stuff.

**Comment by Serg-Norseman** [comment]
I actually froze the project since 2009. However, in 2015, for entertainment, I ported it to Java. What also regretted, because now I would prefer to see it in C# - it would be easier for me sometimes to deal with them in these years.

Forgot to say that all the tiles of the terrain, creatures and objects of the original Ragnarok / Valhalla game were extracted by a special program during the game into the original and accumulated in the cache, after which all were processed. Therefore, I think that almost all the graphics have been extracted from the original.

Among other things, at the very beginning, a one-time connection was established with one of the authors, and he was not against creating a remake. However, he could not help the source code or anything else.

**Comment by Serg-Norseman** [comment]
Last weeks I have a desire to create a small roguelike game in a new setting, in which no other games have been created (it seems that the search did not yield anything). And since I now program almost everything in C#, it would be more convenient to create a common kernel if NWR were written in C#. But alas ... Of course I can port the game from Java to C# (such things are my hobby), but it will take so much time ....

**Comment by Serg-Norseman** [comment]
Forgot to say that all the tiles of the terrain, creatures and objects of the original Ragnarok / Valhalla game were extracted by a special program during the game into the original and accumulated in the cache, after which all were processed. Therefore, I think that almost all the graphics have been extracted from the original.

**Comment by Serg-Norseman** [comment]
Among other things, at the very beginning, a one-time connection was established with one of the authors, and he was not against creating a remake. However, he could not help the source code or anything else.

**Comment by jpka** [comment]
Interesting, thanks for the info.

**Comment by Serg-Norseman** [comment]
Do you like the original and you want to play a more modern version? Or even to develop such?

**Comment by Serg-Norseman** [comment]
In the description of the project (readme) there is an error: the ASCII-mode of the game previously existed (we experimented with different representations), but was later liquidated. However, an isometric view is realized, but for him there is a catastrophic lack of tiles and sprites.
